// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_red_alien_collector__master = "CgkI6dv-2sEdEAIQEg"; // <GPGSID>
        public const string achievement_alien_collector__intermediate = "CgkI6dv-2sEdEAIQFA"; // <GPGSID>
        public const string event_total_green_aliens_collected = "CgkI6dv-2sEdEAIQAQ"; // <GPGSID>
        public const string event_total_blue_aliens_collected = "CgkI6dv-2sEdEAIQAg"; // <GPGSID>
        public const string achievement_red_alien_collector__intermediate = "CgkI6dv-2sEdEAIQEQ"; // <GPGSID>
        public const string achievement_red_alien_collector__novice = "CgkI6dv-2sEdEAIQEA"; // <GPGSID>
        public const string achievement_beat_level_1 = "CgkI6dv-2sEdEAIQBw"; // <GPGSID>
        public const string achievement_thrifty = "CgkI6dv-2sEdEAIQFg"; // <GPGSID>
        public const string event_total_aliens_collected = "CgkI6dv-2sEdEAIQBA"; // <GPGSID>
        public const string achievement_beat_level_2 = "CgkI6dv-2sEdEAIQCA"; // <GPGSID>
        public const string achievement_green_alien_collector__novice = "CgkI6dv-2sEdEAIQCg"; // <GPGSID>
        public const string achievement_alien_collector__master = "CgkI6dv-2sEdEAIQFQ"; // <GPGSID>
        public const string event_total_money_spent = "CgkI6dv-2sEdEAIQBg"; // <GPGSID>
        public const string achievement_blue_alien_collector__master = "CgkI6dv-2sEdEAIQDw"; // <GPGSID>
        public const string achievement_beat_level_3 = "CgkI6dv-2sEdEAIQCQ"; // <GPGSID>
        public const string event_total_red_aliens_collected = "CgkI6dv-2sEdEAIQAw"; // <GPGSID>
        public const string achievement_blue_alien_collector__intermediate = "CgkI6dv-2sEdEAIQDg"; // <GPGSID>
        public const string achievement_green_alien_collector__master = "CgkI6dv-2sEdEAIQDA"; // <GPGSID>
        public const string event_total_money_earned = "CgkI6dv-2sEdEAIQBQ"; // <GPGSID>
        public const string achievement_alien_collector__novice = "CgkI6dv-2sEdEAIQEw"; // <GPGSID>
        public const string achievement_big_spender = "CgkI6dv-2sEdEAIQFw"; // <GPGSID>
        public const string achievement_green_alien_collector__intermediate = "CgkI6dv-2sEdEAIQCw"; // <GPGSID>
        public const string achievement_blue_alien_collector__novice = "CgkI6dv-2sEdEAIQDQ"; // <GPGSID>

}

